######################################################################
##
## Filename: tb_Mul.udo
## Created on: Thu Sep 13 16:12:37 GMT Summer Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
